import { Platform, StyleSheet } from 'react-native';
import type { CustomerThemeColors } from './customerTheme';

export const AUTH_SCREEN_BACKGROUND = '#0f172a';

export function createCustomerAppStyles(colors: CustomerThemeColors) {
  return StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.elevation1,
  },
  safeAreaTransparent: {
    backgroundColor: 'transparent',
  },
  authLoadingShell: {
    flex: 1,
    width: '100%',
    alignSelf: 'stretch',
    backgroundColor: AUTH_SCREEN_BACKGROUND,
  },
  authLoadingTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#e2e8f0',
  },
  topNavBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 10,
    minHeight: 48,
    backgroundColor: colors.elevation0,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.borderLight,
  },
  topNavLogo: {
    width: 120,
    height: 36,
    justifyContent: 'center',
  },
  topNavLogoImage: {
    width: 120,
    height: 36,
  },
  topNavLogoText: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.primary,
  },
  topNavBell: {
    padding: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  topNavActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  topNavPriceListButton: {
    height: 34,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.primary,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primaryLight,
  },
  topNavPriceListButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.primaryDark,
  },
  topNavBranchTrigger: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
    flexShrink: 1,
    minWidth: 0,
    marginRight: 8,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.borderLight,
    backgroundColor: colors.elevation2,
  },
  topNavBranchTriggerStatic: {
    opacity: 1,
  },
  topNavBranchLogoSmall: {
    width: 40,
    height: 40,
    borderRadius: 10,
    flexShrink: 0,
    backgroundColor: colors.elevation0,
  },
  topNavBranchLogoSmallInitial: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  topNavBranchLogoSmallInitialText: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.primaryDark,
  },
  topNavBranchNameText: {
    flex: 1,
    flexShrink: 1,
    minWidth: 0,
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
  },
  container: {
    flex: 1,
    paddingHorizontal: 0,
    justifyContent: 'center',
  },
  containerWithNav: {
    justifyContent: 'flex-start',
  },
  containerAuthBleed: {
    flex: 1,
    width: '100%',
    backgroundColor: 'transparent',
  },
  mainWithNav: {
    flex: 1,
  },
  mainWithNavDesktop: {
    flex: 1,
    width: '100%',
    maxWidth: 920,
    alignSelf: 'center',
  },
  authShellDesktop: {
    flex: 1,
    width: '100%',
    maxWidth: 560,
    alignSelf: 'center',
  },
  contentArea: {
    flex: 1,
    backgroundColor: colors.elevation1,
  },
  homeLayout: {
    flex: 1,
    backgroundColor: colors.elevation1,
  },
  homeMainScroll: {
    flex: 1,
  },
  homeScrollContent: {
    backgroundColor: colors.elevation1,
    paddingBottom: 20,
  },
  homeWelcomeCard: {
    marginTop: 4,
  },
  bottomNavWrapper: {
    paddingHorizontal: 16,
    paddingBottom: 28,
    paddingTop: 8,
    alignItems: 'center',
    backgroundColor: colors.elevation0,
  },
  bottomNav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.navBarDark,
    borderRadius: 28,
    paddingVertical: 10,
    paddingHorizontal: 16,
    height: 80,
    width: '100%',
    maxWidth: 480,
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 12,
    position: 'relative',
  },
  navSideGroupLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    columnGap: 12,
  },
  navSideGroupRight: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    columnGap: 12,
  },
  navItem: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    paddingHorizontal: 4,
    gap: 4,
    minWidth: 56,
  },
  navItemActive: {
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.14)',
    marginHorizontal: 2,
    marginVertical: 2,
  },
  navItemText: {
    fontSize: 11,
    color: colors.navBarIcon,
    fontWeight: '500',
  },
  navItemTextActive: {
    color: colors.white,
    fontWeight: '600',
  },
  navCenterSlot: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 0,
  },
  navBookNowButton: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: colors.primary,
    borderWidth: 6,
    borderColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -32,
  },
  navBookNowLabel: {
    fontSize: 10,
    color: colors.white,
    fontWeight: '700',
    marginTop: 4,
  },
  centered: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  card: {
    borderRadius: 18,
    padding: 24,
    marginHorizontal: 12,
    backgroundColor: colors.elevation3,
    shadowColor: colors.primaryDark,
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 12,
    elevation: 3,
  },
  activeOrdersSection: {
    marginTop: 4,
    marginBottom: 12,
  },
  noActiveOrdersWrapper: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noActiveOrdersText: {
    fontSize: 16,
    color: colors.textSecondary,
    fontWeight: '500',
  },
  activeOrdersTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.primaryDark,
    marginHorizontal: 12,
    marginBottom: 12,
  },
  activeOrdersScroll: {
    paddingHorizontal: 12,
    gap: 12,
    flexDirection: 'row',
    paddingRight: 24,
  },
  activeOrderCard: {
    width: 200,
    minHeight: 160,
    padding: 14,
    borderRadius: 12,
    backgroundColor: colors.primaryDark,
    borderWidth: 0,
    flexDirection: 'column',
    alignItems: 'stretch',
  },
  activeOrderCardLeft: {
    flex: 1,
    minWidth: 0,
    justifyContent: 'flex-start',
  },
  activeOrderCardStatus: {
    marginTop: 8,
    alignSelf: 'flex-start',
  },
  activeOrderCardTop: {
    flex: 1,
    minHeight: 0,
  },
  activeOrderCardPayment: {
    marginTop: 8,
  },
  activeOrderCardRight: {
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    alignSelf: 'stretch',
    paddingLeft: 8,
    minWidth: 100,
  },
  activeOrderId: {
    fontSize: 11,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.88)',
    marginBottom: 6,
  },
  activeOrderTag: {
    alignSelf: 'flex-start',
    backgroundColor: colors.white,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
    marginTop: 4,
    marginBottom: 6,
  },
  activeOrderTagText: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.primaryDark,
  },
  activeOrderServiceLine: {
    fontSize: 12,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.95)',
    marginBottom: 2,
  },
  activeOrderDateLine: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.72)',
  },
  activeOrderPaidTickCircle: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeOrderPaidRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  activeOrderPaidText: {
    fontSize: 12,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.95)',
  },
  activeOrderPaymentFailed: {
    fontSize: 11,
    fontWeight: '600',
    color: '#fecaca',
    marginBottom: 4,
  },
  activeOrderToPay: {
    fontSize: 12,
    fontWeight: '600',
    color: '#fde68a',
    marginBottom: 4,
  },
  activeOrderMeta: {
    fontSize: 11,
    color: colors.textSecondary,
    marginTop: 4,
  },
  activeOrderStatus: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.primaryDark,
  },
  activeOrderStatusChip: {
    alignSelf: 'flex-start',
    backgroundColor: colors.white,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
  },
  activeOrderStatusChipText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.primaryDark,
  },
  activeOrderStatusChipTextCancelled: {
    color: colors.error,
  },
  welcomeScreenOuter: {
    flex: 1,
    width: '100%',
    alignSelf: 'stretch',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 24,
    backgroundColor: AUTH_SCREEN_BACKGROUND,
  },
  branchPickerScreenOuter: {
    flex: 1,
    width: '100%',
    alignSelf: 'stretch',
    justifyContent: 'flex-start',
    alignItems: 'stretch',
    backgroundColor: AUTH_SCREEN_BACKGROUND,
  },
  phoneAuthRoot: {
    flex: 1,
    width: '100%',
    alignSelf: 'stretch',
    backgroundColor: AUTH_SCREEN_BACKGROUND,
  },
  phoneAuthBody: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 20,
  },
  phoneAuthCard: {
    width: '100%',
    maxWidth: Platform.OS === 'web' ? 560 : 420,
    alignSelf: 'center',
    backgroundColor: colors.authCardSurface,
    borderRadius: 26,
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 14,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 12,
    elevation: 4,
    minHeight: Platform.OS === 'web' ? 560 : 0,
  },
  phoneAuthLogoWrap: {
    width: '100%',
    height: Platform.OS === 'web' ? 220 : 110,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
  },
  phoneAuthLogo: {
    width: Platform.OS === 'web' ? 220 : 230,
    height: '100%',
  },
  phoneAuthLogoFallback: {
    width: Platform.OS === 'web' ? 220 : 230,
    height: '100%',
    borderRadius: 20,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  phoneAuthLogoFallbackText: {
    fontSize: 42,
    fontWeight: '700',
    color: colors.white,
    letterSpacing: 1,
  },
  phoneAuthInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'stretch',
    width: '100%',
    minWidth: 0,
    marginTop: 0,
  },
  phoneAuthCountryCodeInput: {
    width: 62,
    minWidth: 62,
    maxWidth: 62,
    marginRight: 6,
    marginBottom: 0,
    paddingHorizontal: 6,
    textAlign: 'center',
    flexShrink: 0,
    height: 52,
  },
  phoneAuthMobileInput: {
    flex: 1,
    minWidth: 0,
    marginBottom: 0,
    height: 52,
  },
  phoneAuthTermsBlock: {
    marginTop: 12,
    marginBottom: 14,
  },
  phoneAuthSubmitBtn: {
    marginTop: 0,
  },
  phoneAuthCreditRow: {
    marginTop: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  welcomeCard: {
    borderRadius: 26,
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 14,
    marginHorizontal: 0,
    backgroundColor: '#dbeafe',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 12,
    elevation: 4,
    alignSelf: 'center',
    width: '100%',
    maxWidth: Platform.OS === 'web' ? 560 : 420,
    minHeight: 0,
  },
  welcomeHeader: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  welcomeLogoFrame: {
    width: '100%',
    height: Platform.OS === 'web' ? 220 : 110,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  welcomeLogo: {
    width: Platform.OS === 'web' ? 220 : 230,
    height: '100%',
    marginBottom: 0,
  },
  welcomeLogoPlaceholder: {
    width: Platform.OS === 'web' ? 220 : 230,
    height: '100%',
    borderRadius: 20,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 0,
  },
  welcomeLogoPlaceholderText: {
    fontSize: 42,
    fontWeight: '700',
    color: colors.white,
    letterSpacing: 1,
  },
  welcomeSubtitle: {
    fontSize: 15,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  termsPrivacyBlock: {
    marginTop: 12,
    marginBottom: Platform.OS === 'web' ? 8 : 8,
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  checkboxRowTouchable: {
    alignSelf: 'stretch',
  },
  checkboxTouchTarget: {
    padding: 4,
    margin: -4,
  },
  termsCheckbox: {
    width: 22,
    height: 22,
    borderWidth: 2,
    borderColor: colors.primary,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  termsCheckboxChecked: {
    backgroundColor: colors.primary,
  },
  checkboxLabel: {
    flex: 1,
    fontSize: 14,
    color: colors.text,
    lineHeight: 20,
  },
  linkText: {
    color: colors.primary,
    fontWeight: '600',
    textDecorationLine: 'underline',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    padding: 24,
  },
  modalCard: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 20,
    maxHeight: '80%',
  },
  modalButtonRow: {
    flexDirection: 'row',
    marginTop: 16,
  },
  modalButton: {
    flex: 1,
  },
  modalButtonSpacer: {
    width: 12,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 12,
  },
  modalScroll: {
    maxHeight: 400,
  },
  modalScrollContent: {
    paddingBottom: 16,
  },
  modalBody: {
    fontSize: 14,
    color: colors.text,
    lineHeight: 22,
  },
  notificationsModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    padding: 24,
  },
  notificationsModalCard: {
    backgroundColor: colors.elevation1,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.borderLight,
    maxHeight: '80%',
    overflow: 'hidden',
    paddingBottom: 16,
    shadowColor: colors.primaryDark,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 8,
  },
  notificationsModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
    backgroundColor: colors.elevation0,
  },
  notificationsModalTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  notificationsModalBellIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationsModalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.text,
  },
  notificationsModalCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.elevation2,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  notificationsEmptyState: {
    alignItems: 'center',
    paddingVertical: 40,
    paddingHorizontal: 24,
  },
  notificationsEmptyIconWrap: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: colors.elevation2,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  notificationsEmptyText: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.textSecondary,
    marginBottom: 4,
  },
  notificationsEmptySubtext: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  notificationsListScroll: {
    maxHeight: 360,
    flexGrow: 0,
  },
  notificationsListContent: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 24,
  },
  notificationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 12,
    marginBottom: 6,
    borderRadius: 12,
    backgroundColor: colors.elevation2,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  notificationRowContent: {
    flex: 1,
    minWidth: 0,
  },
  notificationRowTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.text,
  },
  notificationRowBody: {
    fontSize: 13,
    color: colors.textSecondary,
    marginTop: 2,
  },
  notificationRowTime: {
    fontSize: 12,
    color: colors.textSecondary,
    marginTop: 4,
  },
  priceListState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingVertical: 28,
    gap: 10,
  },
  priceListSearchInput: {
    marginBottom: 14,
    minHeight: 44,
  },
  priceListContent: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 24,
    gap: 10,
  },
  priceListItemCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.borderLight,
    backgroundColor: colors.elevation2,
    padding: 12,
  },
  priceListItemHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  priceListItemIcon: {
    width: 26,
    height: 26,
    borderRadius: 6,
  },
  priceListItemIconFallback: {
    width: 26,
    height: 26,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primaryLight,
  },
  priceListItemName: {
    flex: 1,
    fontSize: 15,
    fontWeight: '700',
    color: colors.text,
  },
  priceListLines: {
    gap: 6,
  },
  priceListLineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    borderRadius: 8,
    backgroundColor: colors.elevation0,
    borderWidth: 1,
    borderColor: colors.borderLight,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  priceListLineLabel: {
    flex: 1,
    fontSize: 13,
    color: colors.text,
  },
  priceListLinePrice: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.primaryDark,
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
    marginBottom: 8,
    color: colors.text,
  },
  subtitle: {
    fontSize: 14,
    color: colors.textSecondary,
    marginBottom: 16,
  },
  orderDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginBottom: 16,
    gap: 8,
  },
  orderDetailLabel: {
    fontSize: 14,
    color: colors.textSecondary,
  },
  orderDetailValue: {
    fontSize: 14,
    color: '#000000',
    flex: 1,
  },
  statusChip: {
    backgroundColor: colors.primaryLight,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.primary,
  },
  statusChipText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.primaryDark,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    marginBottom: 12,
    backgroundColor: colors.elevation2,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
    marginBottom: 6,
  },
  inputReadOnly: {
    backgroundColor: colors.elevation1,
    color: colors.textSecondary,
  },
  /** Login phone row: keep both fields inside the card on narrow widths (e.g. Galaxy Z Fold). */
  phoneInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'stretch',
    width: '100%',
    minWidth: 0,
    marginTop: 6,
    marginBottom: 0,
  },
  countryCodeInput: {
    width: 62,
    minWidth: 62,
    maxWidth: 62,
    marginRight: 6,
    marginBottom: 0,
    paddingHorizontal: 6,
    textAlign: 'center',
    flexShrink: 0,
    height: 52,
  },
  mobileInput: {
    flex: 1,
    minWidth: 0,
    marginBottom: 0,
    height: 52,
  },
  datePickerButton: {
    justifyContent: 'center',
    borderColor: colors.primaryLight,
    borderWidth: 1,
    borderRadius: 10,
    backgroundColor: colors.white,
  },
  datePickerButtonText: {
    fontSize: 16,
    color: colors.primary,
    fontWeight: '700',
  },
  datePickerPlaceholder: {
    fontSize: 16,
    color: colors.textSecondary,
  },
  webCalendarBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.20)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
  },
  webCalendarCard: {
    backgroundColor: colors.white,
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    width: '100%',
    maxWidth: 340,
    maxHeight: 460,
  },
  webCalendarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  webCalendarTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.primaryDark,
  },
  webCalendarNavBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.elevation2,
  },
  webCalendarNavText: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.primaryDark,
  },
  webCalendarWeekRow: {
    flexDirection: 'row',
    marginBottom: 4,
  },
  webCalendarWeekText: {
    flex: 1,
    textAlign: 'center',
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '600',
  },
  webCalendarDaysGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  webCalendarDayCell: {
    width: '14.2857%',
    aspectRatio: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    marginBottom: 2,
  },
  webCalendarDayText: {
    fontSize: 14,
    color: colors.text,
    fontWeight: '500',
  },
  webCalendarDaySelected: {
    backgroundColor: colors.primary,
  },
  webCalendarDayTextSelected: {
    color: colors.white,
    fontWeight: '700',
  },
  webCalendarHolidayDay: {
    backgroundColor: '#fff1f2',
  },
  webCalendarHolidayText: {
    color: '#dc2626',
    fontWeight: '700',
  },
  webCalendarDayDisabled: {
    opacity: 0.55,
  },
  button: {
    backgroundColor: colors.primary,
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonPrimary: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingVertical: 12,
    marginTop: 2,
  },
  rowButton: {
    flex: 1,
  },
  buttonDisabled: {
    opacity: 0.7,
  },
  buttonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '600',
  },
  buttonSecondary: {
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
    backgroundColor: colors.elevation2,
  },
  buttonSecondaryText: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '500',
  },
  textButton: {
    marginTop: 12,
    alignItems: 'center',
  },
  textButtonText: {
    color: colors.textSecondary,
    fontSize: 14,
    textDecorationLine: 'underline',
  },
  profileLogoutButton: {
    marginTop: 24,
    borderColor: colors.error,
  },
  profileLogoutText: {
    color: colors.error,
    fontWeight: '600',
  },
  profileAccountSettingsRow: {
    marginTop: 4,
  },
  profileAccountSettingItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 0,
    gap: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.borderLight,
  },
  profileAccountSettingText: {
    fontSize: 15,
    color: colors.text,
    fontWeight: '500',
  },
  error: {
    color: colors.error,
    marginBottom: 8,
    fontSize: 13,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  orderFilterRow: {
    flexDirection: 'row',
    flexWrap: 'nowrap',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  orderFilterChip: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: colors.borderLight,
    backgroundColor: colors.elevation2,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 0,
  },
  orderFilterChipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  orderFilterChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  orderFilterChipTextActive: {
    color: colors.white,
  },
  plansTabToggle: {
    flexDirection: 'row',
    width: '100%',
    marginBottom: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.elevation2,
    padding: 3,
  },
  plansTabToggleSegment: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  plansTabToggleSegmentActive: {
    backgroundColor: colors.primaryLight,
    borderWidth: 1,
    borderColor: colors.primary,
  },
  plansTabToggleText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  plansTabToggleTextActive: {
    color: colors.primaryDark,
  },
  scroll: {
    flex: 1,
    backgroundColor: colors.elevation1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 0,
    paddingVertical: 24,
    paddingBottom: 48,
    backgroundColor: colors.elevation1,
  },
  scrollContentNoTopPadding: {
    paddingTop: 0,
  },
  branchSelectScroll: {
    flex: 1,
    width: '100%',
    alignSelf: 'stretch',
    backgroundColor: 'transparent',
  },
  branchSelectScrollContent: {
    flexGrow: 1,
    paddingTop: 8,
    paddingBottom: 40,
    paddingHorizontal: 16,
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  branchSearchInput: {
    alignSelf: 'stretch',
    marginBottom: 10,
  },
  branchPincodeInput: {
    alignSelf: 'stretch',
    marginBottom: 12,
  },
  confirmScrollContent: {
    paddingBottom: 120,
  },
  confirmSummaryCard: {
    borderWidth: 1,
    borderColor: colors.borderLight,
    backgroundColor: colors.elevation0,
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
  },
  confirmSummaryLabel: {
    fontSize: 12,
    color: colors.textSecondary,
    fontWeight: '600',
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  confirmSummaryLabelInline: {
    fontSize: 13,
    color: colors.textSecondary,
    fontWeight: '600',
  },
  confirmSummaryValue: {
    fontSize: 16,
    color: colors.text,
    fontWeight: '600',
    marginBottom: 4,
  },
  confirmSummarySubValue: {
    fontSize: 14,
    color: colors.textSecondary,
    marginBottom: 10,
    lineHeight: 20,
  },
  confirmMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: colors.primaryLight,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 10,
    marginBottom: 8,
  },
  confirmSummaryHighlight: {
    fontSize: 15,
    color: colors.primary,
    fontWeight: '700',
  },
  floatingSubmitWrapper: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 32,
    alignItems: 'center',
  },
  floatingSubmitButton: {
    backgroundColor: colors.primary,
    paddingVertical: 18,
    paddingHorizontal: 48,
    borderRadius: 28,
    minWidth: 200,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 12,
  },
  floatingSubmitText: {
    color: colors.white,
    fontSize: 18,
    fontWeight: '700',
  },
  carouselWrapper: {
    width: '100%',
    alignSelf: 'stretch',
    marginBottom: 4,
  },
  carouselContent: {
    paddingVertical: 0,
    paddingHorizontal: 0,
  },
  carouselSlide: {
    overflow: 'hidden',
    backgroundColor: colors.elevation2,
    alignSelf: 'stretch',
  },
  carouselImage: {
    width: '100%',
    height: '100%',
  },
  carouselPlaceholderInner: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.elevation2,
  },
  tileGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 16,
  },
  serviceTile: {
    width: '47%',
    minHeight: 88,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: colors.borderLight,
    backgroundColor: colors.elevation2,
    padding: 16,
    justifyContent: 'center',
  },
  serviceTileSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.elevation3,
  },
  serviceIcon: {
    fontSize: 28,
    marginBottom: 6,
  },
  serviceIconImage: {
    width: 42,
    height: 42,
    marginBottom: 8,
    resizeMode: 'contain',
  },
  serviceLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  serviceLabelSelected: {
    color: colors.text,
  },
  muted: {
    fontSize: 13,
    color: colors.textSecondary,
    marginBottom: 8,
  },
  creditNote: {
    marginTop: 0,
    fontSize: 12,
    color: colors.textSecondary,
    textAlign: 'left',
    flexShrink: 1,
  },
  creditRow: {
    marginTop: 'auto',
    paddingTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  creditRowOnDark: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  creditNoteOnDark: {
    marginTop: 0,
    fontSize: 11,
    color: '#e2e8f0',
    textAlign: 'left',
    flexShrink: 1,
  },
  creditLogo: {
    width: 22,
    height: 22,
  },
  addressCard: {
    padding: 12,
    backgroundColor: colors.elevation2,
    borderRadius: 8,
    marginBottom: 10,
  },
  branchPickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  branchPickerLogo: {
    width: 48,
    height: 48,
    borderRadius: 10,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
  },
  branchPickerLogoInitial: {
    width: 48,
    height: 48,
    borderRadius: 10,
    backgroundColor: colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  branchPickerLogoInitialText: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.primaryDark,
  },
  branchPickerName: {
    flex: 1,
    marginBottom: 0,
  },
  branchActiveOrdersChip: {
    backgroundColor: colors.primaryLight,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
    flexShrink: 0,
    maxWidth: 140,
  },
  branchActiveOrdersChipText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.primaryDark,
  },
  plansPageWrapper: {
    marginHorizontal: 12,
    padding: 24,
  },
  contentPageWrapper: {
    marginHorizontal: 12,
    padding: 24,
  },
  plansSubtitleOneLine: {
    marginBottom: 8,
  },
  plansAddressSection: {
    marginBottom: 12,
  },
  addressCardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    backgroundColor: colors.elevation2,
    borderRadius: 8,
    marginBottom: 8,
  },
  addressCardRowNotServed: {
    borderLeftWidth: 4,
    borderLeftColor: '#d97706',
  },
  addressNotServedLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#b45309',
    marginTop: 6,
  },
  addressSwitchBranchLink: {
    marginTop: 6,
    fontSize: 13,
    fontWeight: '700',
    color: colors.primary,
  },
  editAddressButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 8,
    paddingLeft: 12,
  },
  editAddressButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.primary,
  },
  defaultAddressTag: {
    backgroundColor: colors.primaryLight,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
  },
  defaultAddressTagText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.primaryDark,
  },
  deleteAddressButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 8,
    paddingLeft: 8,
  },
  deleteAddressButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.error,
  },
  googleMapsOpenRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: colors.elevation2,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  googleMapsOpenText: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: colors.primary,
  },
  googleMapsModalContainer: {
    flex: 1,
    backgroundColor: colors.elevation0,
  },
  googleMapsModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
    backgroundColor: colors.elevation1,
  },
  googleMapsModalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.text,
  },
  googleMapsCloseBtn: {
    padding: 4,
  },
  googleMapsWebView: {
    flex: 1,
    backgroundColor: colors.elevation0,
  },
  googleMapsModalFooter: {
    padding: 16,
    paddingBottom: 24,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
    backgroundColor: colors.elevation1,
  },
  orderTileCard: {
    position: 'relative',
  },
  /** Orders tab — ongoing orders: same primary fill as home `activeOrderCard`. */
  orderListActiveCard: {
    position: 'relative',
    padding: 14,
    backgroundColor: colors.primaryDark,
    borderRadius: 12,
    marginBottom: 8,
    borderWidth: 0,
  },
  orderListActiveSecondary: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.72)',
    marginTop: 6,
  },
  orderListActiveUtil: {
    fontSize: 13,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.95)',
    marginTop: 4,
  },
  orderTileHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 4,
  },
  orderTileOrderId: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
  },
  orderTileTag: {
    backgroundColor: colors.primary,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    flexShrink: 0,
  },
  orderTileTagText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.white,
  },
  orderTileStatusRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 8,
  },
  orderTileStatusText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.primary,
  },
  orderTileStatusCancelled: {
    color: colors.error,
  },
  addressLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.text,
    marginBottom: 4,
  },
  orderAmount: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.success,
    marginTop: 6,
  },
  orderAmountPaidRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 6,
  },
  paidTickCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  orderAmountPaid: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.primary,
  },
  amountToPayBox: {
    marginTop: 16,
    marginBottom: 8,
    padding: 16,
    backgroundColor: colors.successBg,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.successBorder,
  },
  amountToPayLabel: {
    fontSize: 14,
    color: colors.success,
    fontWeight: '600',
    marginBottom: 4,
  },
  amountToPayValue: {
    fontSize: 22,
    fontWeight: '700',
    color: '#14532d',
  },
  amountPaidBox: {
    marginTop: 16,
    marginBottom: 8,
    padding: 16,
    backgroundColor: colors.elevation3,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.primaryLight,
  },
  amountPaidBoxGradient: {
    marginTop: 16,
    marginBottom: 8,
    padding: 16,
    borderRadius: 12,
    overflow: 'hidden',
  },
  paidTickCircleOnGreen: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: 'rgba(255,255,255,0.25)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  amountPaidLabelOnGradient: {
    fontSize: 14,
    color: colors.white,
    fontWeight: '600',
    marginBottom: 4,
  },
  amountPaidValueOnGradient: {
    fontSize: 22,
    fontWeight: '700',
    color: colors.white,
  },
  amountPaidMutedOnGradient: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.85)',
    marginTop: 4,
  },
  amountPaidLabel: {
    fontSize: 14,
    color: colors.primary,
    fontWeight: '600',
    marginBottom: 4,
  },
  amountPaidValue: {
    fontSize: 22,
    fontWeight: '700',
    color: colors.primaryDark,
  },
  invoiceRow: {
    marginBottom: 12,
  },
  invoiceTypeLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 10,
    textTransform: 'uppercase',
  },
  invoiceItemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
    paddingVertical: 4,
    borderBottomWidth: 1,
    borderBottomColor: colors.elevation2,
  },
  invoiceItemIcon: {
    width: 24,
    height: 24,
    marginRight: 8,
    borderRadius: 4,
  },
  invoiceItemName: {
    flex: 1,
    fontSize: 14,
    color: colors.textSecondary,
    marginRight: 12,
  },
  invoiceItemNameNoIcon: {},
  invoiceItemAmount: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
  },
  invoiceTotals: {
    marginTop: 8,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
  },
  invoiceTotalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  invoiceTotalLabel: {
    fontSize: 14,
    color: colors.textSecondary,
  },
  invoiceTotalValue: {
    fontSize: 14,
    color: colors.textSecondary,
  },
  invoiceTotalRowFinal: {
    marginTop: 6,
    marginBottom: 0,
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  invoiceTotalLabelFinal: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
  },
  invoiceTotalValueFinal: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
  },
  invoiceActions: {
    flexDirection: 'row',
    marginTop: 10,
    gap: 10,
  },
  invoicePreviewContainer: {
    height: 360,
    borderRadius: 8,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.borderLight,
    backgroundColor: colors.elevation2,
  },
  invoicePreviewWebView: {
    flex: 1,
  },
  invoiceCta: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44,
  },
  invoiceCtaDownload: {
    backgroundColor: colors.elevation2,
    borderWidth: 1,
    borderColor: colors.border,
  },
  invoiceCtaShare: {
    backgroundColor: colors.primary,
  },
  invoiceCtaText: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.text,
  },
  addressLine: {
    fontSize: 14,
    color: colors.textSecondary,
    marginBottom: 2,
  },
  addressPincode: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  link: {
    fontSize: 12,
    color: colors.primary,
    marginTop: 4,
  },
  serviceabilityBox: {
    marginTop: 12,
    padding: 12,
    borderRadius: 8,
    backgroundColor: colors.successBg,
    borderWidth: 1,
    borderColor: colors.successBorder,
  },
  serviceabilityBoxNotServiceable: {
    backgroundColor: '#fef2f2',
    borderColor: '#fecaca',
  },
  serviceableText: {
    fontSize: 14,
    color: colors.success,
    fontWeight: '500',
  },
  notServiceableText: {
    fontSize: 14,
    color: colors.error,
    fontWeight: '600',
    marginBottom: 4,
  },
  notServiceableSubtext: {
    fontSize: 13,
    color: colors.textSecondary,
    marginBottom: 10,
  },
  areaRequestButton: {
    marginTop: 4,
  },
  checkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    paddingVertical: 4,
    minHeight: 44,
  },
  checkbox: {
    fontSize: 28,
    marginRight: 12,
    minWidth: 36,
    minHeight: 36,
    textAlignVertical: 'center',
  },
  checkLabel: {
    fontSize: 16,
    color: colors.text,
    flex: 1,
  },
});
}
